dist: focal
sudo: required
language: python
python: ['3.6']
install:
  - emacs --version
  - git clone https://github.com/riscy/melpazoid.git ~/melpazoid
  - pip install ~/melpazoid
env:
  - RECIPE='(shx :repo "riscy/shx-for-emacs" :fetcher github)' EXIST_OK=true
script:
  - emacs -Q --script ./test/script.el
  - make -C ~/melpazoid
